### ISSUE TITLE
Install Android Emulator Step Fails

### ISSUE THREAD

**Issue by Kyonru** [react-native-community/react-native-circleci-orb#89]
### Orb version
version: 2.1

<details><summary>config.yml</summary>
<p>

```yml

version: 2.1

orbs:
  rn: react-native-community/react-native@5.1.0

jobs:
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '12'
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  analyse_js:
    executor:
      name: rn/linux_js
      node_version: '12'
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn jest
          name: Run Tests

workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_release
          project_path: 'android'
          build_type: release
          requires:
            - analyse_js
      - rn/android_test:
          detox_configuration: 'android.emu.release'
          device_name: Pixel_2_API_29
          platform_version: android-29
          build_tools_version: '29.0.3'
          yarn_cache: false
          requires:
            - build_android_release

        # Build and test the iOS app in release mode
      - rn/ios_build_and_test:
          checkout: true
          project_path: 'ios/dollaridePassengerMobile.xcworkspace'
          project_type: workspace
          device: 'iPhone 11'
          pod_install_directory: ios
          build_configuration: 'Release'
          scheme: 'dollaridePassengerMobile'
          detox_configuration: 'ios.sim.release'
          yarn_cache: false
          xcodebuild_cache: false
          requires:
            - analyse_js

```
</p>
</details>

### What happened

Build fails at step "Install Android Emulator".

![image](https://user-images.githubusercontent.com/17935828/112850733-47cca000-9078-11eb-99f9-a93998e0121d.png)

<details><summary>Error transcript</summary>
<p>

```bash

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```
</p>
</details>

### Expected behavior

The emulator is installed, the app installed, and the e2e tests running.

**Comment by Kyonru** [comment]
If anyone is looking for a workaround, I basically recreated the `android_test` job. 

There might be a solution more elegant than this lol.
<details><summary>workarround</summary>
<p>


```yml
  android_e2e_test:
    executor:
      name: rn/macos
    steps:
      - attach_workspace:
          at: .
      - rn/setup_macos_executor:
          node_version: '12'
      - rn/yarn_install:
          cache: false
      - run:
          command: >
            java -version

            brew tap adoptopenjdk/openjdk

            brew install --cask adoptopenjdk/openjdk/adoptopenjdk8

            java -version

            export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

            mkdir -p ~/.android && touch ~/.android/repositories.cfg

            java -version

            yes | sdkmanager "platform-tools" "tools" >/dev/null

            yes | sdkmanager "platforms;android-29"
            "system-images;android-29;default;x86_64" >/dev/null

            yes | sdkmanager "emulator" --channel=3 >/dev/null

            yes | sdkmanager "build-tools;29.0.2" >/dev/null

            yes | sdkmanager --licenses >/dev/null

            yes | sdkmanager --list
          name: Install Android Emulator
          shell: /bin/bash -e
      - run:
          command: |
            adb start-server
            adb devices
            adb kill-server
            ls -la ~/.android
          name: ADB Start Stop
      - run:
          command: |
            export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
            avdmanager create avd --force --name Pixel_2_API_29 --package "system-images;android-29;default;x86_64" --tag default --device pixel
          name: Create Android Emulator
      - run:
          background: true
          command: |
            export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
            $ANDROID_HOME/emulator/emulator @Pixel_2_API_29 -version
            $ANDROID_HOME/emulator/emulator @Pixel_2_API_29 -cores 1 -gpu auto
            -accel on -memory 1024 -no-audio -no-snapshot -no-boot-anim
            -no-window -logcat *:W | grep -i
            'ReactNative\|com.reactnativecommunity'
          name: Start Android Emulator (background)
      - run:
          command: >
            # export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

            export BOOT=""

            echo "Waiting for AVD to finish booting"

            export PATH=$(dirname $(dirname $(command -v
            android)))/platform-tools:$PATH

            until [[ "$BOOT" =~ "1" ]]; do
              sleep 5
              export BOOT=$(adb -e shell getprop sys.boot_completed 2>&1)
            done

            sleep 15

            adb shell settings put global window_animation_scale 0

            adb shell settings put global transition_animation_scale 0

            adb shell settings put global animator_duration_scale 0

            echo "Android Virtual Device is now ready."
          name: Wait for AVD to be ready
          no_output_timeout: 5m
      - rn/detox_test:
          configuration: 'android.emu.release'
          loglevel: 'warn'
```

</p>
</details>

**Comment by vjoby-wavefin** [comment]
is this issue fixed?

**Comment by ronwsmith** [comment]
@Kyonru I was able to come up with a more elegant solution to this issue:

```
      - react-native/android_test:
          should_on_after_initialize: true
          on_after_initialize: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap adoptopenjdk/openjdk
            HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask adoptopenjdk/openjdk/adoptopenjdk8
            echo 'export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)' >> $BASH_ENV
```
